[package]
name = "aws-sdk-rust"
version = "0.1.6"
authors = ["Chris Jones <chris.jones@lambdastack.io>"]
license = "Apache-2.0"
readme = "README.md"
keywords = ["aws", "s3"]
repository = "https://github.com/lambdastackio/aws-sdk-rust"
homepage = "https://github.com/lambdastackio/aws-sdk-rust"
documentation = "https://github.com/lambdastackio/aws-sdk-rust"
description = """
BETA! - AWS SDK for Rust (only S3 currently). Allows for proxies. For a full AWS SDK look at rusoto. WIP and under heavy development with possible breaking changes - warning.
"""

[dependencies]
chrono = "0.2.21"
httparse = "1.1.2"
hyper = "0.9.10"
log = "0.3.6"
openssl = "0.7.9"
regex = "0.1.65"
rustc-serialize = "0.3.19"
serde = "0.8.0"
serde_json = "0.8.0"
time = "0.1.35"
url = "1.2.0"
xml-rs = "0.1.26"
