[package]
name = "aws-sdk-rust"
version = "0.1.9"
authors = ["Chris Jones <chris.jones@lambdastack.io>"]
license = "Apache-2.0"
readme = "README.md"
keywords = ["aws", "s3"]
repository = "https://github.com/lambdastackio/aws-sdk-rust"
homepage = "https://github.com/lambdastackio/aws-sdk-rust"
documentation = "https://lambdastackio.github.io/aws-sdk-rust/aws_sdk_rust/aws"
description = """
BETA! - Possible breaking changes. V2 signatures are being tested now and V4 signatures will be made whole soon! AWS SDK for Rust (only S3 currently). Allows for proxies. For a full AWS SDK look at rusoto.
"""

[dependencies]
chrono = "0.2.21"
httparse = "1.1.2"
hyper = "0.9.10"
log = "0.3.6"
openssl = "0.7.9"
regex = "0.1.65"
rustc-serialize = "0.3.19"
serde = "0.8.0"
serde_json = "0.8.0"
time = "0.1.35"
url = "1.2.0"
xml-rs = "0.1.26"

# This section is here because there is a main.rs that used as an example.
[[bin]]
doc = false
name = "main"
path = "src/main.rs"
